#!/bin/bash

sqlite3 /opt/atramhasis_gent/atramhasis_gent.sqlite "INSERT INTO conceptscheme VALUES (1, 'urn:x-atramhasis_gent:words')"
sqlite3 /opt/atramhasis_gent/atramhasis_gent.sqlite "INSERT INTO conceptscheme VALUES (2, 'urn:x-atramhasis_gent:score')"

CONF_FILE=/opt/atramhasis_gent/atramhasis_gent/skos/__init__.py


cat > "$CONF_FILE" << EOM
# -*- coding: utf-8 -*-

import logging
log = logging.getLogger(__name__)

from skosprovider_sqlalchemy.providers import SQLAlchemyProvider

def includeme(config):
    ATRAM_GENT = SQLAlchemyProvider(
    {
        'id': 'GENT_WORDS',
        'conceptscheme_id': 1
    },
    config.registry.dbmaker
    )

    ATRAM_SCORE = SQLAlchemyProvider(
    {
        'id': 'SCORE_TAX',
        'conceptscheme_id': 2
    },
    config.registry.dbmaker
    )

    skosregis = config.get_skos_registry()

    skosregis.register_provider(ATRAM_GENT)
    skosregis.register_provider(ATRAM_SCORE)
EOM

